#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Plot mean_score_q95 curves for ALL CSV files in a folder.

Each CSV should be generated by Uncertainty_tail_trend_plot.py and contain:
  - time_s
  - mean_score_q95

This script:
  - scans a folder for *.csv
  - reads each CSV's (time_s, mean_score_q95)
  - optionally filters time_s >= ignore_first_s
  - plots all curves on one figure (one line per CSV)

Outputs:
  <out_prefix>_mean_score_q95_multi.png
"""

import os
import glob
import argparse
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


def parse_mark_times(s: str):
    s = (s or "").strip()
    if not s:
        return []
    out = []
    for tok in s.split(","):
        tok = tok.strip()
        if not tok:
            continue
        try:
            out.append(float(tok))
        except Exception:
            pass
    return out


def read_mean_score_q95(csv_path: str) -> pd.DataFrame:
    df = pd.read_csv(csv_path)
    need = ["time_s", "mean_score_q95"]
    miss = [c for c in need if c not in df.columns]
    if miss:
        raise ValueError(f"[{os.path.basename(csv_path)}] missing columns: {miss}")

    df = df[need].copy()
    df["time_s"] = pd.to_numeric(df["time_s"], errors="coerce")
    df["mean_score_q95"] = pd.to_numeric(df["mean_score_q95"], errors="coerce")
    df = df.dropna(subset=["time_s"])
    # de-dup time (safe)
    df = df.groupby("time_s", as_index=False).mean(numeric_only=True)
    df = df.sort_values("time_s").reset_index(drop=True)
    return df


if __name__ == "__main__":
    ap = argparse.ArgumentParser()

    ap.add_argument("--csv_dir", type=str, default="/home/ferry/data/Code2/Research/Inhand_Activate/plot/Q3/csv_uncertainty_3", help="Folder containing csv files.")
    ap.add_argument("--pattern", type=str, default="*.csv", help="Glob pattern inside folder (default *.csv).")
    ap.add_argument("--ignore_first_s", type=float, default=6.0, help="Filter time_s >= this value (default 3).")

    ap.add_argument("--mark_times", type=str, default="6,12,18,24,30", help="Vertical markers, comma-separated.")
    ap.add_argument("--out_prefix", type=str, default="", help="Output prefix (default: <csv_dir>/mean_score_q95_multi)")

    ap.add_argument("--legend_mode", type=str, default="stem", choices=["stem", "full"],
                    help="Legend label mode: stem=filename without extension; full=full filename.")

    args = ap.parse_args()

    csv_dir = os.path.abspath(args.csv_dir)
    if not os.path.isdir(csv_dir):
        raise ValueError(f"Not a directory: {csv_dir}")

    if not args.out_prefix:
        args.out_prefix = os.path.join(csv_dir, "mean_score_q95_multi")

    mark_times = parse_mark_times(args.mark_times)

    paths = sorted(glob.glob(os.path.join(csv_dir, args.pattern)))
    if not paths:
        raise RuntimeError(f"No CSV matched: {os.path.join(csv_dir, args.pattern)}")

    plt.figure()

    loaded = 0
    for p in paths:
        try:
            df = read_mean_score_q95(p)
        except Exception as e:
            print(f"[Skip] {os.path.basename(p)} ({type(e).__name__}: {e})")
            continue

        if args.ignore_first_s is not None and args.ignore_first_s > 0:
            df = df[df["time_s"] >= float(args.ignore_first_s)].reset_index(drop=True)

        if df.empty:
            print(f"[Skip] {os.path.basename(p)} (empty after filtering)")
            continue

        label = os.path.basename(p) if args.legend_mode == "full" else os.path.splitext(os.path.basename(p))[0]
        plt.plot(df["time_s"].to_numpy(), df["mean_score_q95"].to_numpy(), label=label, linewidth=2.0)
        loaded += 1

    if loaded == 0:
        raise RuntimeError("No valid CSV loaded. Check columns/time ranges.")

    for mt in mark_times:
        plt.axvline(float(mt), linewidth=1.0)

    plt.xlabel("Time (s)")
    plt.ylabel("mean_score_q95")
    plt.title("Mean Score Q95 Trend (multiple CSVs)")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()

    out_png = args.out_prefix + "_mean_score_q95_multi.png"
    os.makedirs(os.path.dirname(out_png), exist_ok=True)
    plt.savefig(out_png, dpi=200)

    print(f"[Done] saved: {out_png}")
    print(f"[Info] plotted {loaded} curves from {len(paths)} csv files.")
