"""
@FileName：npy2ply.py
@Description：
@Author：Ferry
@Time：2025 11/29/25 12:01 AM
@Copyright：©2024-2025 ShanghaiTech University-RIMLAB
"""
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
npy2ply.py

Convert a .npy point cloud file to .ply format.

Supported input shapes:
- (N, 3): x, y, z
- (N, 6): x, y, z, r, g, b
- (N, 7): x, y, z, r, g, b, a

Color values can be either:
- float in [0, 1]
- int/float in [0, 255]
"""

import argparse
import os
import numpy as np


def infer_mode(data):
    """Infer data mode from shape. Return 'xyz', 'xyzrgb', or 'xyzrgba'."""
    if data.ndim != 2:
        raise ValueError(f"Expected 2D array, got shape {data.shape}")

    c = data.shape[1]
    if c == 3:
        return "xyz"
    elif c == 6:
        return "xyzrgb"
    elif c == 7:
        return "xyzrgba"
    else:
        # Fallback：只用前3维当xyz
        print(f"[Warning] Unsupported channel count {c}, "
              f"fallback to 'xyz' using first 3 columns.")
        return "xyz"


def to_uint8_color(color_array):
    """
    Convert color array to uint8 in [0,255].
    Accepts either [0,1] or [0,255] range.
    """
    color_array = np.asarray(color_array)

    if color_array.size == 0:
        return color_array.astype(np.uint8)

    max_val = float(color_array.max())
    min_val = float(color_array.min())

    if max_val <= 1.0 and min_val >= 0.0:
        # assume [0,1]
        color_array = color_array * 255.0

    color_array = np.clip(color_array, 0, 255)
    return color_array.astype(np.uint8)


def write_ply(filename, points, colors=None, alpha=None):
    """
    Write point cloud to ASCII PLY.

    points: (N,3) float
    colors: (N,3) uint8 or None
    alpha:  (N,)  uint8 or None
    """
    n_points = points.shape[0]
    use_color = colors is not None
    use_alpha = alpha is not None

    with open(filename, "w") as f:
        # Header
        f.write("ply\n")
        f.write("format ascii 1.0\n")
        f.write("comment Generated by npy2ply.py\n")
        f.write(f"element vertex {n_points}\n")
        f.write("property float x\n")
        f.write("property float y\n")
        f.write("property float z\n")
        if use_color:
            f.write("property uchar red\n")
            f.write("property uchar green\n")
            f.write("property uchar blue\n")
        if use_alpha:
            f.write("property uchar alpha\n")
        f.write("end_header\n")

        # Data
        if not use_color and not use_alpha:
            for p in points:
                f.write(f"{p[0]} {p[1]} {p[2]}\n")
        elif use_color and not use_alpha:
            for p, c in zip(points, colors):
                f.write(f"{p[0]} {p[1]} {p[2]} {int(c[0])} {int(c[1])} {int(c[2])}\n")
        else:
            for p, c, a in zip(points, colors, alpha):
                f.write(f"{p[0]} {p[1]} {p[2]} {int(c[0])} {int(c[1])} {int(c[2])} {int(a)}\n")


def main():
    parser = argparse.ArgumentParser(description="Convert .npy point cloud to .ply")
    parser.add_argument("input", type=str, default="outer.npy", help="Input .npy file")
    parser.add_argument("output", type=str,nargs="?", help="Output .ply file")
    parser.add_argument(
        "--mode",
        type=str,
        default="auto",
        choices=["auto", "xyz", "xyzrgb", "xyzrgba"],
        help="Interpretation of channels (default: auto by shape)",
    )
    args = parser.parse_args()

    in_path = args.input
    out_path = args.output

    if out_path is None:
        base, _ = os.path.splitext(in_path)
        out_path = base + ".ply"

    data = np.load(in_path)
    if data.ndim != 2:
        raise ValueError(f"Expected 2D array, got shape {data.shape}")

    if args.mode == "auto":
        mode = infer_mode(data)
    else:
        mode = args.mode

    if mode == "xyz":
        points = data[:, :3].astype(np.float32)
        colors = None
        alpha = None
    elif mode == "xyzrgb":
        points = data[:, :3].astype(np.float32)
        rgb = data[:, 3:6]
        colors = to_uint8_color(rgb)
        alpha = None
    elif mode == "xyzrgba":
        points = data[:, :3].astype(np.float32)
        rgb = data[:, 3:6]
        a = data[:, 6]
        colors = to_uint8_color(rgb)
        alpha = to_uint8_color(a)
    else:
        raise ValueError(f"Unknown mode: {mode}")

    print(f"[Info] mode={mode}, points={points.shape[0]}")
    write_ply(out_path, points, colors, alpha)
    print(f"[Done] Saved to: {out_path}")


if __name__ == "__main__":
    main()
